name: Run All Tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r integrations/langchain/requirements.txt
    - name: Run all tests
      run: |
        python integrations/langchain/test_crud.py